In [1]:
import numpy as np

In [2]:
my_list = []

In [5]:
my_list.append(1)
my_list.append(2)
my_list.append(3)

In [6]:
my_list

[1, 2, 3]

In [7]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [8]:
np.zeros(shape=(3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [27]:
np.random.seed(101)
np.random.randint(1, 100, 20)

array([96, 12, 82, 71, 64, 88, 76, 10, 78, 41,  5, 64, 41, 61, 93, 65,  6,
       13, 94, 41])

In [26]:
np.random.randint(1, 100, 20)

array([37, 64, 20, 36, 31, 11, 61, 21, 28,  9, 87, 27, 88, 47, 48, 55, 87,
       10, 46,  3])

In [31]:
arr = np.random.randint(0, 100, 10)
arr

array([76, 95, 87,  0, 73,  8, 62, 36, 83, 99])

In [34]:
print(str(arr.min()) + " " + str(arr.argmin()))
print(str(arr.max()) + " " + str(arr.argmax()))

0 3
99 9


In [39]:
arr.reshape(2, 5).argmin()

3

In [48]:
new_arr = np.random.randint(0, 100, 100).reshape((10, 10))
new_arr

array([[88, 76, 93, 83, 95, 68, 69, 59, 52,  7],
       [40, 73, 86, 14, 49, 97, 25, 57, 40, 17],
       [32, 83, 97, 27, 47, 13, 70, 15, 92, 18],
       [94, 48, 65, 82, 34,  5, 46, 83, 27, 26],
       [20, 87, 84, 17, 59, 64, 44,  4, 51, 49],
       [74, 82, 37, 53, 93, 73,  5, 37, 56, 35],
       [15, 40, 42, 71, 37, 46, 71, 91, 97, 36],
       [43, 27, 66, 57,  3, 55, 70, 41, 67, 72],
       [88, 67, 75, 69, 92, 20, 15, 57,  9, 69],
       [97, 91, 51, 54, 45, 38, 15, 42, 61,  8]])

In [51]:
print(new_arr[:,1])
print(new_arr[1, 1])

[76 73 83 48 87 82 40 27 67 91]
73
